### ISSUE TITLE
Explore VT judiciary court-hearings api

### ISSUE THREAD

**Issue by lucas-johnson** [codeforbtv/courtbot-vt#12]
### Description
Newly discovered court calendar api: https://www.vermontjudiciary.org/court-hearings

This does not break  our current parsing (this repo) & storing ([court-calendar repo](https://github.com/codeforbtv/court-calendars)) workflow, but it may make it obsolete... Which is a good thing, but we need to do some exploration first to see what we can do with this api. 

### Questions
- Do we have unlimited access to the API? 
- Given an identifier (docket, county, division) can we extract court event information efficiently such that we don't need to scrape, format, and store the same in our own "database"? Thinking about performance and the user experience here – folks don't want to wait more than a few seconds for a request. 
- Does it make sense to set up a python library offering utility functions for accessing this API? Thinking this would be in line with the codeForTulsa [oscn](https://github.com/codefortulsa/oscn) library?

**Comment by iamyume** [comment]
Closing this since now we have access to daily excel files.
