### ISSUE TITLE
Courtbot subscription currently only sends notifications for one event

### ISSUE THREAD

**Issue by iritush** [codeforbtv/courtbot-vt#28]
Need to confirm accuracy of this description:
When a user subscribes to courtbot notifications, the notifications being sent are only for one (next?) event. 
Workaround:
To get notifications for any other event, the user must resubscribe

**Comment by iamyume** [comment]
This ticket should probably be moved to https://github.com/codeforbtv/courtbot-vt-frontend/ project since that deals with handling all the notifications and sms responses.

This project only deals with getting the data, parsing it, and writing it to the database.

**Comment by courtneyfay** [comment]
moved this to frontend issues https://github.com/codeforbtv/courtbot-vt-frontend/issues/8, gonna close here
