### ISSUE TITLE
Deploy to the cloud

### ISSUE THREAD

**Issue by lucas-johnson** [codeforbtv/courtbot-vt#3]
# 🍦 Feature Request 🍦 

- Set up a simple server with python 3. 
- Set up a courtbot-vt github account with write access to [court-calendars]( https://github.com/codeforbtv/court-calendars).
- Clone the repo and install necessary packages.
- Create a cron job to run the [main script](https://github.com/codeforbtv/courtbot-vt/blob/main/main.py) daily (as a start).

**Comment by IamSMOF** [comment]
Not needed now that we don't use court-calendars repo.
