### ISSUE TITLE
Support different court calendar styles

### ISSUE THREAD

**Issue by lucas-johnson** [codeforbtv/courtbot-vt#5]
# 🍦 Feature Request 🍦 

### Current Behavior
We only parse html block text style calendars like https://www.vermontjudiciary.org/courts/court-calendars/bns_cal.htm. To my knowledge, this html block text calendar style currently covers ~90% of VT court calendars.
### Desired Updates/Changes
- Add parsing capabilities for probate courts and similar (e.g. https://www.vermontjudiciary.org/court-hearings?f[0]=hearings_county%3A10&f[1]=court_division_taxonomy_term_name%3Aprobate)
- Refactor code to allow for various parsers. This should allow us to more easily adapt to changing court calendars.

**Comment by iamyume** [comment]
Closing this since now we have access to daily excel files.
