### ISSUE TITLE
Protect main branch in court-calendars repo

### ISSUE THREAD

**Issue by lucas-johnson** [codeforbtv/courtbot-vt#6]
# 🍦 Feature Request 🍦 

### Current Behavior
Any user with access to [court-calendars](https://github.com/codeforbtv/court-calendars) can write to the main branch (i.e. our database). 
### Desired Updates/Changes
Restrict access to [court-calendars](https://github.com/codeforbtv/court-calendars) main branch such that only a courtbot-vt (bot) github account can write.  This is probably dependent on https://github.com/codeforbtv/courtbot-vt/issues/3.

**Comment by IamSMOF** [comment]
I don't think this is relevant any more now that we're not using the GitHub "Court-Calendars" repo as our "database."
