### ISSUE TITLE
Make setup windows compatible

### ISSUE THREAD

**Issue by lucas-johnson** [codeforbtv/courtbot-vt#7]
The `Setup and Run` portion of the [README](https://github.com/codeforbtv/courtbot-vt/blob/main/README.md), and all of the associated code was developed on a Mac with MacOS/Linux in mind... So this setup process should at least be tested on Windows, and potentially updated/modified to support Windows.

**Comment by IamSMOF** [comment]
A fix to the read-me fixed this a while back.
